### ISSUE TITLE
No Refactor button in Animation editor

### ISSUE THREAD

**Issue by BarbarianBunny** [poohcom1/godot-animation-player-refactor#7]
No Refactor button is added in the Animation drop down menu.

I'm using Godot 4.3 and this is the only addon I have in my project.
I downloaded the addon through AssetLib and restarted Godot just incase that mattered.

Since I tried this addon only with 4.3 I do not know if this is an issue specific to 4.3

**Comment by poohcom1** [comment]
Hi, can you give me a minimal reproduction project? And just to confirm, you've activated the plugin in the Project Settings, right?

**Comment by BarbarianBunny** [comment]
Well, this is embarrassing. I didn't realize i had to activate it. I haven't messed with addons at all before this.

It's working now, though I had to do a little refactoring to avoid naming conflicts.

Thank you for your quick response.
